CC 	= gcc
CCFLAG 	= -g -O3 -Wall -Wextra -pedantic -Wno-unused-parameter -g -Wdeclaration-after-statement -Wmissing-declarations -Wpointer-arith -Wstrict-prototypes -Wredundant-decls -Wcast-align -Wwrite-strings -Winline -Wformat-security -Wformat-nonliteral -Wswitch-enum -Wswitch-default -Winit-self
LD 	= gcc
LDFLAG 	= 
AR 	= ar
ARFLAG 	= 
RANLIB 	= ranlib
RM	= rm
ECHO	= echo
SHELL 	= /bin/sh
MAKE	= make
MFLAG	= 
.SILENT	:

