#!/usr/bin/env python

env = Environment(	CC = 'gcc', 
			CCFLAGS = '-g -Wall -Wextra -Wno-unused-parameter ',
			LINKFLAGS = ' ',
			LIBS = ['IL','ILU','m'], 
			LIBPATH = '.' )
env.Program(	'a.bin', 
		[	'hlColorSpace.c', 
			'hlColor.c',
			'hlTile.c',
			'hlRaw.c',
			'hlImg.c',
			'hlFrame.c',
			'hlAdjOp.c',
			'hlRegion.c',
			'hlADT.c',
			'hlOp.c',
			'hlBlendOp.c',
			'hlDrawOp.c',
			'hlInit.c'])


#Scons examples in case you need it...
#Library('foo', ['a.c','b.c'] )
#Program('bar', ['d.c','e.c'], LIBS=['foo'], LIBPATH='.')
